services:
  app:
    build:
      context: .
      args:
        - IMAGE_TAG_PREFIX
        - PHP_VERSION
    platform: linux/amd64
    links:
      - consul
      - mysql
      - nacos
      - oracle
      - php-fpm
      - pgsql
      - redis
      - wordpress
    environment:
      DISABLE_DEFAULT_SERVER: 1
      GITHUB_ACTIONS: "yes"
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - wordpress:/var/www/html

  php-fpm:
    image: php:8.4-fpm
    volumes:
      - .:/var/www

  wordpress:
    image: wordpress:php8.4-fpm
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: test
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
        volume:
          nocopy: false

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  pgsql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  oracle:
    image: gvenzl/oracle-xe:slim
    platform: linux/amd64
    environment:
      ORACLE_PASSWORD: oracle

  redis:
    image: redis:7.2

  nacos:
    image: nacos/nacos-server
    platform: linux/amd64
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname

  consul:
    image: consul:1.15
    command:
      consul agent -dev -client=0.0.0.0

volumes:
  wordpress:
