name: Static Analysis

on: [ push, pull_request, workflow_dispatch ]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    container:
      image: phpswoole/swoole:6.0-php8.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP And Swoole
        run: |
          set -e
          echo "swoole.enable_library=Off" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
          composer require --dev -n -q --no-progress -- phpstan/phpstan=~2.0

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse --no-progress --memory-limit 2G
